#!/usr/bin/env python

import getpass
import json
import nacl.secret
import nacl.utils
import os
import re
import scrypt
import sys

pw  = {}
cur = None

try:
    with open(sys.argv[1] + '.txt', "r") as in_file:
        for line in in_file:
            match = re.match('(name|site|username|password|extra)\s*:\s*([^\n]+)',
                             line)
            if match:
                (name, value) = match.group(1,2)
                if (name == 'name'):
                    cur = pw[value] = {}
                else:
                    cur[name] = value

    with open(os.path.expanduser('~/.pw/' + sys.argv[1] + '.pw'), "w") as out_file:
        password = getpass.getpass();
        salt = nacl.utils.random(64)
        key = scrypt.hash(password, salt, buflen=32)
        box = nacl.secret.SecretBox(key)
        nonce = nacl.utils.random(nacl.secret.SecretBox.NONCE_SIZE)
        encrypted = box.encrypt(json.dumps(pw), nonce)
        out_file.write(salt)
        out_file.write(encrypted)

    print "imported {} credentials.".format(len(pw))

except (IOError, nacl.exceptions.CryptoError) as e:
    print e

except IndexError:
    print "usage: {} <pw-file-suffix>".format(sys.argv[0])
