#!/usr/bin/env python

import argparse
import json
import os
import re
import sys

fields        = 'site', 'username', 'password', 'extra'
max_field_len = len(max(fields, key=len))

def lookup_credential(pw, search_term):

    for name in [x for x in pw if re.search(search_term, x,
                                                  re.I)]:
        info = pw[name]
        print "\n{}\n{}".format(name, '-'*len(name))

        for field in fields:
            if field in info:
                print "{0:{1}} : {2}".format(field, max_field_len,
                                             info[field])

def prompt(pw):
    try:
        while True:
            line = raw_input('>>>')
            lookup_credential(pw, line)
            print
    except EOFError:
        pass

try:
    file = os.path.expanduser('~/.pw/' + sys.argv[1] + '.pw')
    with open(file, "r") as pw_file:

        pw = json.load(pw_file)

        if len(sys.argv) == 2:
            prompt(pw)
        else:
            lookup_credential(pw, sys.argv[2])
    print

except IOError, e:
    print e

except IndexError:
    print "usage: {} <pw-file> <credential-name>".format(sys.argv[0])
